<?php
$class = array(
		array("00","GENERALITES"),
		//array("00.0","Generalites misc."),
		array("00.1"," Généralités sur les sciences"),
		array("00.2","Enseignement - Recherche"),
		array("00.3","Linguistique"),
		array("00.4","Techniques documentaires"),
		array("01","MATHEMATIQUES"),
		//array("01.0","Mathematiques misc."),
		array("01.1","Mathématiques pour application à une autre discipline"),
		array("01.2","Fondement des mathématiques"),
		array("01.3","Algèbre et théorie des nombres"),
		array("01.4","Géométrie"),
		array("01.5","Topologie"),
		array("01.6","Analyse"),
		array("01.7","Analyse numérique - Recherche opérationnelle"),
		array("01.8","Probabilités, statistiques et applications"),
		array("01.9","Autres sujets"),
		array("02","INFORMATIQUE ET AUTOMATIQUE"),
		//array("02.0","Informatique misc."),
		array("02.1","Informatique théorique"),
		array("02.2","Programmation - Logiciels"),
		array("02.3","Informatique répartie et temps partagé"),
		array("02.4","Matériel"),
		array("02.5","Applications"),
		array("02.6","Théorie des systèmes / Automatique et informatique industrielle"),
		array("02.7","Intelligence artificielle"),
		array("03","PHYSIQUE"),
		//array("03.0","Physique misc."),
		array("03.1","Physique théorique"),
		array("03.2","Physique atomique et moléculaire - Physique nucléaire"),
		array("03.3","Electricité - Magnétisme - Electromagnétisme"),
		array("03.4","Optique"),
		array("03.5","Acoustique - Electroacoustique"),
		array("03.6","Thermodynamique"),
		array("03.7","Mécanique des solides et des fluides"),
		array("03.8","Physique de la matière condensée / Physique des gaz et des plasmas"),
		array("03.9","Sciences et techniques de la terre et de l'univers"),
		array("04","CHIMIE ET SCIENCES DE LA VIE"),
		//array("04.0","Chimie misc."),
		array("04.1","Chimie générale - Chimie physique"),
		array("04.2","Chimie minérale"),
		array("04.3","Chimie organique"),
		array("04.4","Chimie analytique"),
		array("04.5","Génie chimique et chimie industrielle"),
		array("04.6","Sciences de la vie"),
		array("05","ELECTRONIQUE ET MICROELECTRONIQUE / ELECTROTECHNIQUE - ENERGIE"),
		//array("05.0","Electronique misc."),
		array("05.1","Electronique générale"),
		array("05.2","Electronique des semiconducteurs, microélectronique et optoélectronique"),
		array("05.3","Circuits électriques, filtres, lignes de transmission"),
		array("05.4","Affichage"),
		array("05.5","Applications diverses de l'electronique"),
		array("05.6","Electrotechnique - Energie électrique"),
		array("06","TECHNOLOGIES ET TECHNIQUES DE L'INGENIEUR"),
		//array("06.0","Technologies misc."),
		array("06.1","Métallurgie - Matériaux, fabrication et traitements"),
		array("06.2","Dessin industriel"),
		array("06.3","Instrumentation et mesures"),
		array("06.4","Fiabilité - sûreté de fonctionnement"),
		array("06.5","Sécurité - Protection de l'environnement - Pollution"),
		array("06.6","Manutention - Transports - Art militaire"),
		array("06.7","Bâtiment - Travaux publics"),
		array("06.8","Techniques et machines diverses"),
		array("06.9","Industries diverses"),
		array("07","THEORIE DE L'INFORMATION - THEORIE DU SIGNAL ET DES COMMUNICATIONS - TRAITEMENT DU SIGNAL ET DES IMAGES"),
		//array("07.0","Theorie de l'information misc."),
		array("07.1","Théorie de l'information"),
		array("07.2","Théorie du signal, des communications et du bruit"),
		array("07.3","Traitement du signal"),
		array("07.4","Compatibilité électromagnétique"),
		array("08","TELECOMMUNICATIONS - VIDEOCOMMUNICATIONS AUDIOVISUEL"),
		//array("08.0","Telecommunications misc."),
		array("08.1","Généralités sur les télécommunications"),
		array("08.2","Réseaux et services de télécommunications"),
		array("08.3","Réseaux de communication de données ou téléinformatiques - RNIS bande étroite et large bande"),
		array("08.4","Radiocommunication (sauf radiodiffusion)"),
		array("08.5","Radiorepérage et radionavigation"),
		array("08.6","Radiodiffusion sonore et de télévision - Audiovisuel - Vidéocommunication"),
		array("08.7","Réseaux sans fil et mobiles / Wireless and mobile networks"),
		array("09","SCIENCES ECONOMIQUES"),
		//array("09.0","Sciences economiques misc."),
		array("09.1","Théorie économique"),
		array("09.2","Microéconomie"),
		array("09.3","Macroéconomie "),
		array("09.4","Economie internationale"),
		array("09.5","Activités économiques (industrie et services)"),
		array("10","GESTION"),
		//array("10.0","Gestion misc."),
		array("10.1","Acteurs économiques (entreprises, fonction publique, associations …)"),
		array("10.2","Management"),
		array("10.3","Marketing"),
		array("10.4","Finances (Gestion financière)"),
		array("10.5","Ressources humaines"),
		array("10.6","Gestion industrielle"),
		array("10.7","Entrepreneuriat"),
		array("11","DROIT"),
		//array("11.0","Droit misc."),
		array("11.1","Droit public"),
		array("11.2","Droit fiscal"),
		array("11.3","Droit privé"),
		array("11.4","Droit social"),
		array("11.5","Droit communautaire"),
		array("11.6","Droit des Technologies de l'Information et de la Communication (TIC)"),
		array("11.7","Droits sectoriels"),
		array("12","SCIENCES HUMAINES"),
		//array("12.0","Sciences humaines misc."),
		array("12.1","Sociologie"),
		array("12.2","Psychologie"),
		array("12.3","Philosophie"),
		array("12.4","Littérature  et œuvres cinématographiques"),
		array("12.5","Civilisation, histoire et problèmes contemporains / Anthropologie"),
		array("12.6","Géographie"),
		array("12.7","Art et culture")
	);
?>